# fly.toml app configuration file generated for maria-university-project on 2024-04-01T11:18:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maria-university-project'
primary_region = 'ams'

[build]

[env]
  PORT = '5173'

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
